### Quartz 配置
spring:
  application:
    name: job-task
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/flash_framework?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: password
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20

tasks:
  type: elastic_job
  ## 是否开启补偿机制,开启需要配置数据源
  compensate: true
  ## 任务异常是否发通知
  error-message-notice: false
  ## 异常邮件组
  mail-group: zhurg@163.com
  elastic-job:
    namespace: job-task
    server-lists: 127.0.0.1:2181
    ## 使用数据库存储elasticJob自身日志
    enable-datasource: true



error.job.cron: '0 0/5 * * * ?'
error.job.params: "{\"orderCode\":\"1234567\"}"
error.job.compensateCron: '0 0/1 * * * ?'
error.job.mails: 123@qq.com,456@qq.com

